name: 📝 General Issue
description: 其他类型的问题或建议
title: ""
labels: ["needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        欢迎提交任何其他类型的问题或建议！

  - type: textarea
    id: issue-description
    attributes:
      label: 📝 问题描述
      description: 请详细描述你的问题或建议
      placeholder: 描述你的问题或建议...
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: 🏷️ 问题类型
      description: 选择问题类型
      options:
        - 文档改进 - 改进文档
        - 性能优化 - 性能相关
        - 代码质量 - 代码质量相关
        - 测试 - 测试相关
        - 构建 - 构建相关
        - 部署 - 部署相关
        - 其他 - 其他类型
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: ⭐ 优先级
      description: 这个问题的优先级
      options:
        - 低 - 不紧急
        - 中 - 一般
        - 高 - 重要
        - 紧急 - 非常紧急
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 📋 额外信息
      description: 任何其他相关信息
      placeholder: 添加任何其他相关信息...

  - type: checkboxes
    id: terms
    attributes:
      label: 确认
      description: 请确认以下信息
      options:
        - label: 我已经搜索了现有的 issues
          required: true
        - label: 我同意在需要时提供更多信息
          required: true
